/// test_test_mode.cpp — visual regression test for new_register --test mode.
///
/// Usage: test_test_mode <tests_dir>
///
/// Generates the synthetic test volume (identical to --test mode) and renders
/// central axial/sagittal/coronal slices in GrayScale and HotMetal colour maps.
/// Each rendered slice is pixel-compared (±1 tolerance) against reference PNGs
/// in <tests_dir> previously generated by generate_test_mode_refs.
///
/// Reference PNGs:
///   testmode_ax_gray.png   testmode_sa_gray.png   testmode_co_gray.png
///   testmode_ax_hot.png    testmode_sa_hot.png    testmode_co_hot.png

#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"

#include <cmath>
#include <cstdio>
#include <iostream>
#include <string>
#include <vector>

#include "ColourMap.h"
#include "SliceRenderer.h"
#include "Volume.h"

static int testsPassed = 0;
static int testsFailed = 0;

#define TEST(name) \
    std::cerr << "  TEST: " << name << " ... ";

#define PASS() \
    do { std::cerr << "PASS\n"; ++testsPassed; } while (0)

#define FAIL(msg) \
    do { std::cerr << "FAIL: " << msg << "\n"; ++testsFailed; } while (0)

// ---------------------------------------------------------------------------
// PNG comparison — ±1 per channel to absorb integer rounding.
// Returns mismatch count, or -1 on load/size error.
// ---------------------------------------------------------------------------
static int comparePng(const std::string& refPath,
                      const std::vector<uint32_t>& rendered,
                      int width, int height)
{
    int refW = 0, refH = 0, channels = 0;
    unsigned char* data = stbi_load(refPath.c_str(), &refW, &refH, &channels, 4);
    if (!data)
    {
        std::cerr << "\n    [error] cannot load reference PNG: " << refPath << "\n";
        return -1;
    }

    if (refW != width || refH != height)
    {
        std::cerr << "\n    [error] size mismatch: reference " << refW << "x" << refH
                  << " vs rendered " << width << "x" << height << "\n";
        stbi_image_free(data);
        return -1;
    }

    int mismatches = 0;
    for (int i = 0; i < width * height; ++i)
    {
        // rendered: 0xAABBGGRR — R in bits 0-7, G in 8-15, B in 16-23
        uint32_t p = rendered[i];
        int rR = (p >>  0) & 0xFF;
        int rG = (p >>  8) & 0xFF;
        int rB = (p >> 16) & 0xFF;

        // stb_image: interleaved R,G,B,A bytes
        int pR = data[i * 4 + 0];
        int pG = data[i * 4 + 1];
        int pB = data[i * 4 + 2];

        if (std::abs(rR - pR) > 1 || std::abs(rG - pG) > 1 || std::abs(rB - pB) > 1)
            ++mismatches;
    }

    stbi_image_free(data);
    return mismatches;
}

// ---------------------------------------------------------------------------
// Render one slice and compare against its reference PNG.
// ---------------------------------------------------------------------------
static void runTest(const char* name,
                    const Volume& vol,
                    const VolumeRenderParams& params,
                    int viewIndex, int sliceIndex,
                    const std::string& refPath)
{
    TEST(name);
    RenderedSlice s = renderSlice(vol, params, viewIndex, sliceIndex);
    if (s.pixels.empty())
    {
        FAIL("empty slice");
        return;
    }
    int mm = comparePng(refPath, s.pixels, s.width, s.height);
    if (mm < 0)
        FAIL("could not load reference PNG");
    else if (mm > 0)
        FAIL(std::to_string(mm) + " pixel(s) differ from reference");
    else
        PASS();
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------
int main(int argc, char** argv)
{
    if (argc < 2)
    {
        std::cerr << "Usage: test_test_mode <tests_dir>\n";
        return 1;
    }

    std::string dir = argv[1];
    if (!dir.empty() && dir.back() != '/')
        dir += '/';

    Volume vol;
    vol.generate_test_data();
    std::cerr << "Test volume: "
              << vol.dimensions.x << "x" << vol.dimensions.y << "x" << vol.dimensions.z
              << ", range=[" << vol.min_value << "," << vol.max_value << "]\n\n";

    VolumeRenderParams pGray;
    pGray.valueMin  = vol.min_value;
    pGray.valueMax  = vol.max_value;
    pGray.colourMap = ColourMapType::GrayScale;

    VolumeRenderParams pHot;
    pHot.valueMin  = vol.min_value;
    pHot.valueMax  = vol.max_value;
    pHot.colourMap = ColourMapType::HotMetal;

    int cx = vol.dimensions.x / 2;  // sagittal centre
    int cy = vol.dimensions.y / 2;  // coronal  centre
    int cz = vol.dimensions.z / 2;  // axial    centre

    // GrayScale — exercises basic LUT + sphere/grid geometry
    runTest("axial_gray",    vol, pGray, 0, cz, dir + "testmode_ax_gray.png");
    runTest("sagittal_gray", vol, pGray, 1, cx, dir + "testmode_sa_gray.png");
    runTest("coronal_gray",  vol, pGray, 2, cy, dir + "testmode_co_gray.png");

    // HotMetal — exercises a multi-colour LUT to catch per-channel regressions
    runTest("axial_hot",     vol, pHot,  0, cz, dir + "testmode_ax_hot.png");
    runTest("sagittal_hot",  vol, pHot,  1, cx, dir + "testmode_sa_hot.png");
    runTest("coronal_hot",   vol, pHot,  2, cy, dir + "testmode_co_hot.png");

    std::cerr << "\n" << testsPassed << " passed, " << testsFailed << " failed.\n";
    return testsFailed > 0 ? 1 : 0;
}
